[Header]
Scheme_Name = "Generic"
Scheme_Description = "These are the generic feeds which seethru distribute"
Scheme_Author = "SeeThru Networks"
Scheme_Owner = "SeeThru Networks"
Creation_Date = "2020-06-05 12:58:58"

[Api_Keys.generic-key]
Access_Token = "$(GENERIC-KEY_ACCESS_TOKEN)"
Secret = "$(GENERIC-KEY_SECRET)"

[Feeds.MicrosoftTeams]
Script = "MicrosoftTeams"
Api_Key = "generic-key"
Guid = "$(TEAMS_GUID)"

[Feeds.GoogleHangouts]
Script = "GoogleHangouts"
Api_Key = "generic-key"
Guid = "$(HANGOUTS_GUID)"

[Feeds.Zoom]
Script = "Zoom"
Api_Key = "generic-key"
Guid = "$(ZOOM_GUID)"

[Scripts.MicrosoftTeams.Meta]
Script_Name = "MicrosoftTeams"
Script_Output_Path = "Outputs/Teams.json"
Script_Object_Path = "SeeThru_Feeds.Library.Scripts.TCPPortOpen@TCPPortOpen"

[Scripts.MicrosoftTeams.Fillables]
host = "teams.microsoft.com"

[Scripts.GoogleHangouts.Meta]
Script_Name = "GoogleHangouts"
Script_Output_Path = "Outputs/GoogleHangouts.json"
Script_Object_Path = "Scripts.GoogleHangouts@GoogleHangouts"

[Scripts.Zoom.Meta]
Script_Name = "Zoom"
Script_Output_Path = "Outputs/Zoom.json"
Script_Object_Path = "Scripts.Zoom@Zoom"
